[tool.black]
line-length = 105
target-version = ["py311"]

[tool.ruff]
line-length = 105
lint.select = ["E", "F", "W", "I", "C", "Q"]
lint.ignore = ["C901"]
#ignore = ["E203", "W503"]
exclude = ["build", "dist", ".venv", "__pycache__"]

[tool.isort]
profile = "black"